# Generated by Django 3.2.13 on 2022-11-06 17:57

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Admin'), (2, 'Driver'), (3, 'Customer')], default=0)),
                ('firebase_token', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narx', models.CharField(default='Kelishiladi', max_length=600)),
            ],
            options={
                'verbose_name': 'Narx',
                'verbose_name_plural': 'Narxlar',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Viloyatlar',
                'verbose_name_plural': 'Viloyatlar',
            },
        ),
        migrations.CreateModel(
            name='TempOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('olindi', 'Olindi')], default='yangi', max_length=100)),
                ('location', models.TextField(default='Manzil yo`q!')),
                ('person_count', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=100)),
                ('client_phone', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=200)),
                ('create_time', models.TimeField(default=datetime.datetime.now)),
                ('create_date', models.DateField(default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_order_customer', to=settings.AUTH_USER_MODEL)),
                ('price', models.ForeignKey(default='Kelishiladi', on_delete=django.db.models.deletion.CASCADE, related_name='tempbuyurtmanarxi', to='home.price')),
                ('qayerdan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tempqayerdanviloyat', to='home.region')),
                ('qayerga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tempqayergadanviloyat', to='home.region')),
            ],
            options={
                'verbose_name': 'Temp Buyurtmalar',
                'verbose_name_plural': 'Temp Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('kutish', 'Kutish'), ('olindi', 'Olindi')], default='yangi', max_length=100)),
                ('location', models.TextField(default='Manzil yo`q!')),
                ('person_count', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=100)),
                ('client_phone', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=200)),
                ('client_in_car', models.CharField(choices=[('ha', 'Ha'), ('yoq', 'Yo`q')], default='yoq', max_length=200)),
                ('price_nomi', models.CharField(blank=True, max_length=200, null=True)),
                ('qayerdan_nomi', models.CharField(blank=True, max_length=200, null=True)),
                ('qayerga_nomi', models.CharField(blank=True, max_length=200, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('create_time', models.TimeField(default=datetime.datetime.now)),
                ('create_date', models.DateField(default=datetime.datetime.now)),
                ('blacklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderblackdriver', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('price', models.ForeignKey(default='Kelishiladi', on_delete=django.db.models.deletion.CASCADE, related_name='buyurtmanarxi', to='home.price')),
                ('qayerdan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qayerdanviloyat', to='home.region')),
                ('qayerga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qayergadanviloyat', to='home.region')),
            ],
            options={
                'verbose_name': 'Faol Buyurtmalar',
                'verbose_name_plural': 'Faol Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qayerdan', models.CharField(blank=True, max_length=600, null=True)),
                ('qayerga', models.CharField(blank=True, max_length=600, null=True)),
                ('status', models.CharField(choices=[('barchasi', 'Barchasi'), ('filter', 'Filter')], default='barchasi', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filterdriver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filterlar',
                'verbose_name_plural': 'Filterlar',
            },
        ),
        migrations.CreateModel(
            name='ArchiveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yetkazildi', 'Yetkazildi')], default='yetkazildi', max_length=100)),
                ('qayerdan', models.CharField(max_length=1000)),
                ('qayerga', models.CharField(max_length=1000)),
                ('person_count', models.CharField(default=1, max_length=100)),
                ('price', models.CharField(default=100000, max_length=200)),
                ('client_phone', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=200)),
                ('create_time', models.TimeField(default=datetime.datetime.now)),
                ('create_date', models.DateField(default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archorder_customer', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archdriver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arxiv Buyurtmalar',
                'verbose_name_plural': 'Arxiv Buyurtmalar',
            },
        ),
    ]
